FROM golang:1.23-alpine AS builder

ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.io,direct
ENV TZ=Asia/Shanghai

WORKDIR /go/LeapLedger

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY . .

RUN go build -o leapledger

FROM alpine:3.20.3

ENV TZ=Asia/Shanghai
ENV GOROOT=/usr/local/go

WORKDIR /go/LeapLedger

COPY --from=builder /usr/local/go/lib /usr/local/go/lib
COPY --from=builder /go/LeapLedger /go/LeapLedger

EXPOSE 8080

CMD ["./leapledger"]